#!/bin/bash
# Beast Mode Welcome Script

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║   ██████╗ ███████╗ █████╗ ███████╗████████╗                      ║"
echo "║   ██╔══██╗██╔════╝██╔══██╗██╔════╝╚══██╔══╝                      ║"
echo "║   ██████╔╝█████╗  ███████║███████╗   ██║                         ║"
echo "║   ██╔══██╗██╔══╝  ██╔══██║╚════██║   ██║                         ║"
echo "║   ██████╔╝███████╗██║  ██║███████║   ██║                         ║"
echo "║   ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝                         ║"
echo "║                                                                  ║"
echo "║   ███╗   ███╗ ██████╗ ██████╗ ███████╗                           ║"
echo "║   ████╗ ████║██╔═══██╗██╔══██╗██╔════╝                           ║"
echo "║   ██╔████╔██║██║   ██║██║  ██║█████╗                             ║"
echo "║   ██║╚██╔╝██║██║   ██║██║  ██║██╔══╝                             ║"
echo "║   ██║ ╚═╝ ██║╚██████╔╝██████╔╝███████╗                           ║"
echo "║   ╚═╝     ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝                           ║"
echo "║                                                                  ║"
echo "║   MS Graph & GitHub Enterprise Automation Toolkit                ║"
echo "║   Running in WebVM - Browser-based Linux Environment             ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Quick Start:"
echo "  python3 ~/beastmode/scripts/beastmode.py help"
echo "  python3 ~/beastmode/scripts/beastmode.py status"
echo "  python3 ~/beastmode/scripts/beastmode.py config --init"
echo ""
echo "Documentation: ~/beastmode/docs/"
echo "Scripts:       ~/beastmode/scripts/"
echo ""
