#!/bin/bash
# Beast Mode Welcome Script

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║   ██████╗ ███████╗ █████╗ ███████╗████████╗                      ║"
echo "║   ██╔══██╗██╔════╝██╔══██╗██╔════╝╚══██╔══╝                      ║"
echo "║   ██████╔╝█████╗  ███████║███████╗   ██║                         ║"
echo "║   ██╔══██╗██╔══╝  ██╔══██║╚════██║   ██║                         ║"
echo "║   ██████╔╝███████╗██║  ██║███████║   ██║                         ║"
echo "║   ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝                         ║"
echo "║                                                                  ║"
echo "║   ███╗   ███╗ ██████╗ ██████╗ ███████╗                           ║"
echo "║   ████╗ ████║██╔═══██╗██╔══██╗██╔════╝                           ║"
echo "║   ██╔████╔██║██║   ██║██║  ██║█████╗                             ║"
echo "║   ██║╚██╔╝██║██║   ██║██║  ██║██╔══╝                             ║"
echo "║   ██║ ╚═╝ ██║╚██████╔╝██████╔╝███████╗                           ║"
echo "║   ╚═╝     ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝                           ║"
echo "║                                                                  ║"
echo "║   MS Graph & GitHub Enterprise Automation Toolkit                ║"
echo "║   Running in WebVM - Browser-based Linux Environment             ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "┌──────────────────────────────────────────────────────────────────┐"
echo "│  Available Tools:                                                │"
echo "├──────────────────────────────────────────────────────────────────┤"
echo "│  beastmode / bm     - Main Beast Mode CLI                        │"
echo "│  graph-explorer / ge - MS Graph Explorer CLI                     │"
echo "│  gex                - Graph Explorer Interactive Mode            │"
echo "│  azure-shell / azsh - Azure Cloud Shell Helper                   │"
echo "│  graph-sdk          - Graph SDK & Code Generator                 │"
echo "│  org-sync           - Organization Sync Toolkit                  │"
echo "└──────────────────────────────────────────────────────────────────┘"
echo ""
echo "Quick Start:"
echo "  bm help              - Show Beast Mode help"
echo "  ge help              - Show Graph Explorer help"
echo "  gex                  - Start Graph Explorer interactive mode"
echo "  azsh                 - Start Azure Shell interactive mode"
echo "  graph-auth           - Test Graph API authentication"
echo ""
echo "Configuration:"
echo "  ge config --init     - Initialize Graph Explorer config"
echo "  Set environment variables: AZURE_TENANT_ID, AZURE_CLIENT_ID,"
echo "  AZURE_CLIENT_SECRET for authentication"
echo ""
echo "Documentation: ~/beastmode/docs/"
echo ""
